Empleado/urls.py
from django.urls import path
from . import views

app_name = 'empleados'

urlpatterns = [
    path('', views.EmpleadoListView.as_view(), name='all'),
    path('empleado/<int:pk>/detail', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('empleado/create/', views.EmpleadoCreateView.as_view(), name='empleado_create'),
    path('empleado/<int:pk>/update/', views.EmpleadoUpdateView.as_view(), name='empleado_update'),
    path('empleado/<int:pk>/delete/', views.EmpleadoDeleteView.as_view(), name='empleado_delete'),
    path('empleado/reporte/general/', views.ReporteEmpleadosExcel.as_view(), name='reporte_general'),
    path('empleado/<int:pk>/details/', views.DetalleEmpleadoPDF.as_view(), name='details_general')
]

Telefono/urls.py
from django.urls import path
from . import views

app_name = 'telefonos'

urlpatterns = [
    path('telefono/<int:pk>/create/', views.TelefonoCreateView.as_view(), name='telefono_create'),
    path('telefono/<int:pk>/update/', views.TelefonoUpdateView.as_view(), name='Telefono_update'),
    path('telefono/<int:pk>/delete/', views.TelefonoDeleteView.as_view(), name='Telefono_delete'),
]

crud_django_usi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Empleado.urls')),
    path('', include('Telefono.urls')),
    path('', include('Ejercicio.urls'))
]

Telefono/models.py
from django.db import models
from Empleado.models import Empleado


class Telefono(models.Model):
    numero = models.CharField(max_length=20, verbose_name='Numero de telefono')
    ext = models.PositiveIntegerField(verbose_name='Extension')
    tipo = models.CharField(max_length=32, verbose_name='tipo de telefono')

    empleado = models.ForeignKey(Empleado, on_delete=models.DO_NOTHING, related_name='Telefonos')

    def __str__(self):
        return f'({self.ext}){self.numero}'

Telefono/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from Empleado.models import Empleado
from .models import Telefono


class TelefonoBaseView(View):
    model = Telefono
    fields = ['numero', 'ext', 'tipo']
    success_url = reverse_lazy('empleados:all')


class TelefonoCreateView(TelefonoBaseView, CreateView):
    """View to create a new Telefono"""

    def form_valid(self, form):
        telefono = form.save(commit=False)
        telefono.empleado = get_object_or_404(Empleado, id=self.kwargs.get('pk'))

        return super(TelefonoCreateView, self).form_valid(form)

    def get_success_url(self):
        id = self.kwargs.get('pk')

        return reverse('empleados:empleado_update', kwargs={'pk': id})


class TelefonoUpdateView(TelefonoBaseView, UpdateView):
    """View to update a Telefono"""

    def get_success_url(self):
        obj = self.get_object()

        return reverse('empleados:empleado_update', kwargs={'pk': obj.empleado_id})


class TelefonoDeleteView(TelefonoBaseView, DeleteView):
    """View to delete a Telefono"""

    def form_valid(self, form):
        obj = self.get_object()
        id = obj.empleado_id
        obj.delete()

        return HttpResponseRedirect(
            reverse('empleados:empleado_update', kwargs={'pk': id}))

templates/Telefono/telefono_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Eliminar Telefono</h1>

        <p class="h5">¿Estás seguro que deseas eliminar el teléfono?</p>
        <h3 class="my-5">{{ telefono }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirmar" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'empleados:empleado_update' telefono.empleado_id %}'; return false;" value="Cancelar">
        </form>
    </div>
</div>

{% endblock %}

templates/Telefono/telefono_form.html
{% extends "base.html" %}

{% block content %}
<div class="container d-flex mt-8" style="width: 25%;">
    <div class="col">
        <h2 class="text-center">Telefono</h2>
    <p></p>
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{ form }}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Guardar" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'empleados:empleado_detail' 1 %}'; return false;" value="Cancelar">
            </div>
        </form>

    </div>
</div>
{% endblock %}