Empleado/urls.py
from django.urls import path
from . import views

app_name = 'empleados'

urlpatterns = [
    path('', views.EmpleadoListView.as_view(), name='all'),
    path('empleado/<int:pk>/detail', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('empleado/create/', views.EmpleadoCreateView.as_view(), name='empleado_create'),
    path('empleado/<int:pk>/update/', views.EmpleadoUpdateView.as_view(), name='empleado_update'),
    path('empleado/<int:pk>/delete/', views.EmpleadoDeleteView.as_view(), name='empleado_delete'),
    path('empleado/reporte/general/', views.ReporteEmpleadosExcel.as_view(), name='reporte_general'),
    path('empleado/<int:pk>/details/', views.DetalleEmpleadoPDF.as_view(), name='details_general')
]

Telefono/urls.py
from django.urls import path
from . import views

app_name = 'telefonos'

urlpatterns = [
    path('telefono/<int:pk>/create/', views.TelefonoCreateView.as_view(), name='telefono_create'),
    path('telefono/<int:pk>/update/', views.TelefonoUpdateView.as_view(), name='Telefono_update'),
    path('telefono/<int:pk>/delete/', views.TelefonoDeleteView.as_view(), name='Telefono_delete'),
]

crud_django_usi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Empleado.urls')),
    path('', include('Telefono.urls')),
    path('', include('Ejercicio.urls'))
]

Empleado/models.py
from django.db import models


class GradoEstudioCatalogo(models.Model):
    grado = models.CharField(max_length=32, verbose_name="Grado de estudio catalogo")

    def __str__(self):
        return self.grado


class TipoEmpleadoCatalogo(models.Model):
    tipo = models.CharField(max_length=32, verbose_name="Tipo de empleado catalogo")

    def __str__(self):
        return self.tipo


class Empleado(models.Model):
    nombre = models.CharField(max_length=64, verbose_name='Nombre')
    apPaterno = models.CharField(max_length=64, verbose_name='Apellido Paterno')
    apMaterno = models.CharField(max_length=64, verbose_name='Apellido Materno')
    edad = models.IntegerField(verbose_name='Edad')
    genero = models.CharField(max_length=32, verbose_name='Genero')
    puesto = models.CharField(max_length=64, verbose_name='Puesto')

    grado = models.ForeignKey(GradoEstudioCatalogo, verbose_name='Grado', on_delete=models.DO_NOTHING)
    tipo = models.ForeignKey(TipoEmpleadoCatalogo, verbose_name='Tipo de Empledo', on_delete=models.DO_NOTHING)

    activado = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.nombre} {self.apPaterno} {self.apMaterno}'

Empleado/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, DeleteView, TemplateView
from extra_views import InlineFormSetFactory, CreateWithInlinesView, UpdateWithInlinesView
from openpyxl.workbook import Workbook

from django.template.loader import get_template
from xhtml2pdf import pisa

from Direccion.models import Direccion
from Empleado.models import Empleado
from Telefono.models import Telefono


class TelefonoInline(InlineFormSetFactory):
    model = Telefono
    fields = ['numero', 'ext', 'tipo']
    prefix = 'telefono_form'
    factory_kwargs = {'extra': 1, 'max_num': None,
                      'can_order': False, 'can_delete': False}


class DireccionInline(InlineFormSetFactory):
    model = Direccion
    fields = ['entidad', 'calle', 'numero', 'cp']
    prefix = 'direccion_form'
    factory_kwargs = {'extra': 1, 'max_num': None,
                      'can_order': False, 'can_delete': False}


class EmpleadoBaseView(View):
    model = Empleado
    fields = ['nombre', 'apPaterno', 'apMaterno', 'edad', 'genero', 'puesto', 'grado', 'tipo']
    success_url = reverse_lazy('empleados:all')


class EmpleadoListView(EmpleadoBaseView, ListView):
    """View to list all Empleados.
    Use the 'Empleado_list' variable in the template
    to access all Empleado objects"""
    queryset = Empleado.objects.filter(activado=True)


class EmpleadoDetailView(EmpleadoBaseView, DetailView):
    """View to list the details from one Empleado.
    Use the 'Empleado' variable in the template to access
    the specific Empleado here and in the Views below"""


class EmpleadoCreateView(EmpleadoBaseView, CreateWithInlinesView):
    """View to create a new Empleado"""
    inlines = [DireccionInline, TelefonoInline]


class EmpleadoUpdateView(EmpleadoBaseView, UpdateWithInlinesView):
    """View to update a Empleado"""
    template_name = 'Empleado/empleado_form_update.html'
    inlines = [DireccionInline]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['telefonos'] = Telefono.objects.filter(empleado_id=context['pk'])

        return context


class EmpleadoDeleteView(EmpleadoBaseView, DeleteView):
    """View to delete a Empleado"""

    def form_valid(self, form):
        obj = self.get_object()
        obj.activado = False
        obj.save()

        return HttpResponseRedirect(self.get_success_url())


class ReporteEmpleadosExcel(TemplateView):

    def get(self, request, *args, **kwargs):
        empleados = Empleado.objects.filter(activado=True)

        wb = Workbook()
        ws = wb.active

        ws['B1'] = 'REPORTE GENERAL DE EMPLEADOS'
        ws.merge_cells('B1:E1')

        ws.column_dimensions['B'].width = 25
        ws.column_dimensions['C'].width = 25
        ws.column_dimensions['D'].width = 25
        ws.column_dimensions['E'].width = 10
        ws.column_dimensions['F'].width = 20
        ws.column_dimensions['G'].width = 25
        ws.column_dimensions['H'].width = 25
        ws.column_dimensions['I'].width = 25
        ws.column_dimensions['J'].width = 25
        ws.column_dimensions['K'].width = 25
        ws.column_dimensions['L'].width = 10
        ws.column_dimensions['M'].width = 10

        ws['B3'] = 'Nombre'
        ws['C3'] = 'Apellido Paterno'
        ws['D3'] = 'Apellido Materno'
        ws['E3'] = 'Edad'
        ws['F3'] = 'Genero'
        ws['G3'] = 'Puesto'
        ws['H3'] = 'Grado'
        ws['I3'] = 'Tipo Empleado'
        ws['J3'] = 'Entidad Federativa'
        ws['K3'] = 'Calle'
        ws['L3'] = 'Numero'
        ws['M3'] = 'Codigo Postal'
        cont = 4

        for empleado in empleados:
            ws.cell(row=cont, column=2).value = empleado.nombre
            ws.cell(row=cont, column=3).value = empleado.apPaterno
            ws.cell(row=cont, column=4).value = empleado.apMaterno
            ws.cell(row=cont, column=5).value = empleado.edad
            ws.cell(row=cont, column=6).value = empleado.genero
            ws.cell(row=cont, column=7).value = empleado.puesto
            ws.cell(row=cont, column=8).value = empleado.grado.grado
            ws.cell(row=cont, column=9).value = empleado.tipo.tipo
            ws.cell(row=cont, column=10).value = empleado.direccion.entidad.entidad
            ws.cell(row=cont, column=11).value = empleado.direccion.calle
            ws.cell(row=cont, column=12).value = empleado.direccion.numero
            ws.cell(row=cont, column=13).value = empleado.direccion.cp
            cont += 1

        archivo = "ReporteEmpleados.xlsx"

        response = HttpResponse(content_type="application/ms-excel")
        contenido = "attachment; filename={0}".format(archivo)
        response["Content-Disposition"] = contenido
        wb.save(response)

        return response


class DetalleEmpleadoPDF(TemplateView):

    def get(self, request, *args, **kwargs):
        empleado = get_object_or_404(Empleado, id=self.kwargs.get('pk'))

        context = {'empleado': empleado}
        html = render_to_string("Empleado/empleado_details.html", context)

        response = HttpResponse(content_type="application/pdf")
        response["Content-Disposition"] = "inline; report.pdf"

        pisa_status = pisa.CreatePDF(html, dest=response)

        if pisa_status.err:
            return HttpResponse("We had some error <pre>" + html + "</pre>")

        return response

templates/Empleado/empleado_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete Film</h1>

        <p class="h5">¿Estás seguro que deseas eliminar el empleado</p>
        <h3 class="my-5">{{ empleado }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirmar" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'empleados:all' %}'; return false;" value="Cancelar">
        </form>
    </div>
</div>

{% endblock %}

templates/Empleado/empleado_details.html
<h1>Detalles Empleado</h1>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nombre:
        </dt>
        <dd class="col-sm-10">
              &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.nombre }}
        </dd>
        <dt class="col-sm-2">
            Apellido Paterno:
        </dt>
        <dd class="col-sm-10">
             &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.apPaterno }}
        </dd>
        <dt class="col-sm-2">
           Apellido Materno
        </dt>
        <dd class="col-sm-10">
             &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.apMaterno }}
        </dd>
        <dt class="col-sm-2">
            Edad:
        </dt>
        <dd class="col-sm-10">
             &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.edad }}
        </dd>
        <dt class="col-sm-2">
            Genero:
        </dt>
        <dd class="col-sm-10">
             &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.genero }}
        </dd>
        <dt class="col-sm-2">
            Puesto:
        </dt>
        <dd class="col-sm-10">
             &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.puesto }}
        </dd>
        <dt class="col-sm-2">
            Tipo de Empleado:
        </dt>
        <dd class="col-sm-10">
             &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.tipo.tipo }}
        </dd>
        <dt class="col-sm-2">
            Grado de Estudio:
        </dt>
        <dd class="col-sm-10">
             &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.grado.grado }}
        </dd>
    </dl>
</div>

<div>
    <h4>Direccion</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Calle:
        </dt>
        <dd class="col-sm-10">
            &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.direccion.calle }}
        </dd>
        <dt class="col-sm-2">
            Numero:
        </dt>
        <dd class="col-sm-10">
            &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.direccion.numero }}
        </dd>
        <dt class="col-sm-2">
            Codigo postal:
        </dt>
        <dd class="col-sm-10">
            &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.direccion.cp }}
        </dd>
        <dt class="col-sm-2">
            Entidad Federativa:
        </dt>
        <dd class="col-sm-10">
            &nbsp;&nbsp;&nbsp;&nbsp;{{ empleado.direccion.entidad.entidad }}
        </dd>
    </dl>
</div>

<h4>Telefonos</h4>
<hr />
<table class="table">
    <thead>
        <tr>
            <th>
                Telefono
            </th>
            <th>
                Extension
            </th>
            <th>
                Tipo
            </th>
        </tr>
    </thead>
    <tbody>
        {% for telefono in empleado.Telefonos.all %}
            <tr>
                <td>
                    &nbsp;&nbsp;&nbsp;&nbsp;{{ telefono.numero }}
                </td>
                <td>
                    &nbsp;&nbsp;&nbsp;&nbsp;{{ telefono.ext }}
                </td>
                <td>
                    &nbsp;&nbsp;&nbsp;&nbsp;{{ telefono.tipo }}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

templates/Empleado/empleado_form.html
{% extends "base.html" %}

{% block content %}

<div class="container d-flex mt-8" style="width: 25%;">
    <div class="col">
        <h2 class="text-center">Empleado</h2>
    <p></p>
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{ form }}
{#                {{ inlines.direccion_form }}#}
                {% for formset in inlines %}
                    {{ formset }}
                {% endfor %}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Guardar" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'empleados:all' %}'; return false;" value="Cancelar">
            </div>
        </form>

    </div>
</div>

{% endblock %}

templates/Empleado/empleado_form_update.html
{% extends "base.html" %}

{% block content %}

<div class="container d-flex mt-8" style="width: 25%;">
    <div class="col">
        <h2 class="text-center">Editar - Empleado</h2>
    <p></p>
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{ form }}
{#                {{ inlines.direccion_form }}#}
                {% for formset in inlines %}
                    {{ formset }}
                {% endfor %}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Guardar" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;"
                       onclick="window.location='{% url 'empleados:all' %}'; return false;" value="Cancelar">
            </div>
        </form>
        <h2 class="text-center">Telefonos</h2>
        <div class="d-flex justify-content-start">
            <a href="{% url 'telefonos:telefono_create' empleado.id %}"
               class="d-block btn btn-primary btn-lg my-5">Agregar telefono</a>
        </div>
        <table class="table table-striped mt-8">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Numero</th>
                    <th class="text-center" scope="col">Extension</th>
                    <th class="text-center" scope="col">Tipo</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for telefono in telefonos %}
                <tr>
                    <td class="text-center">{{telefono.numero}}</td>
                    <td class="text-center">{{telefono.ext}}</td>
                    <td class="text-center">{{telefono.tipo}}</td>

                    <td><a href="{% url 'telefonos:Telefono_update' telefono.id %} ">Editar</a></td>
                    {% if telefonos.count > 1 %}
                        <td><a href="{% url 'telefonos:Telefono_delete' telefono.id %}">Eliminar</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/Empleado/empleado_list.html
{% extends 'base.html' %}

{% block content %}

    <h1>Empleados</h1>

    <p>
        <a href="{% url 'empleados:empleado_create' %}" >Agregar</a> |
        <a href="{% url 'empleados:reporte_general' %}" >Reporte excel</a>
    </p>

<div class="container d-flex mt-8">
    <div class="col">
        <table class="table table-striped mt-8">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Nombre</th>
                    <th class="text-center" scope="col">Apellido Paterno</th>
                    <th class="text-center" scope="col">Apellido Materno</th>
                    <th class="text-center" scope="col">Edad</th>
                    <th class="text-center" scope="col">Genero</th>
                    <th class="text-center" scope="col">Puesto</th>
                    <th class="text-center" scope="col">Grado</th>
                    <th class="text-center" scope="col">Tipo</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                {% for empleado in empleado_list %}
                <tr>
                    <td class="text-center">{{empleado.nombre}}</td>
                    <td class="text-center">{{empleado.apPaterno}}</td>
                    <td class="text-center">{{empleado.apMaterno}}</td>
                    <td class="text-center">{{empleado.edad}}</td>
                    <td class="text-center">{{empleado.genero}}</td>
                    <td class="text-center">{{empleado.puesto}}</td>
                    <td class="text-center">{{empleado.grado.grado}}</td>
                    <td class="text-center">{{empleado.tipo.tipo}}</td>
                    <td><a href="{% url 'empleados:empleado_update' empleado.id %} ">Editar</a></td>
                    <td><a href="{% url 'empleados:details_general' empleado.id %} ">Detalles PDF</a></td>
                    <td><a href="{% url 'empleados:empleado_delete' empleado.id %}">Eliminar</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% endblock content %}