Ejercicio/urls.py
from django.urls import path
from . import views

app_name = 'ejercicio'

urlpatterns = [
    path('ejercicio/', views.ejercicioView, name='ejercicio')
]

Empleado/urls.py
from django.urls import path
from . import views

app_name = 'empleados'

urlpatterns = [
    path('', views.EmpleadoListView.as_view(), name='all'),
    path('empleado/<int:pk>/detail', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('empleado/create/', views.EmpleadoCreateView.as_view(), name='empleado_create'),
    path('empleado/<int:pk>/update/', views.EmpleadoUpdateView.as_view(), name='empleado_update'),
    path('empleado/<int:pk>/delete/', views.EmpleadoDeleteView.as_view(), name='empleado_delete'),
    path('empleado/reporte/general/', views.ReporteEmpleadosExcel.as_view(), name='reporte_general'),
    path('empleado/<int:pk>/details/', views.DetalleEmpleadoPDF.as_view(), name='details_general')
]

crud_django_usi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Empleado.urls')),
    path('', include('Telefono.urls')),
    path('', include('Ejercicio.urls'))
]

templates/base.html
<!DOCTYPE HTML>
<html lang="en">


{% block head %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
        {% if title %}
            <title>{{title}} | Empleados</title>
        {% else %}
            <title>Empleados</title>
        {% endif %}
    {% endblock title %}
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock head %}


<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ejercicio:ejercicio' %}">Ejercicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'empleados:all' %}">Empleados</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

 <div class="container">
    <main role="main" class="pb-3">
        {% block content %}
        {% endblock content %}
    </main>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>